import { db } from './src/lib/db';

async function seed() {
  console.log('🌱 Seeding Velvet and Veda database...');

  // Clear existing data
  await db.salon.deleteMany();
  await db.testimonial.deleteMany();
  await db.occasion.deleteMany();
  await db.blogPost.deleteMany();

  // Seed Salons - 16 diverse salons with unique images
  const salons = [
    {
      name: "Enrich Beauty Salon & Academy",
      area: "Koramangala",
      address: "80 Feet Road, Koramangala 4th Block, Bangalore - 560034",
      rating: 4.8,
      reviewCount: 2340,
      imageUrl: "/images/hero-bridal.png",
      whatsappNumber: "919845012345",
      phone: "080-25531234",
      priceRange: "₹",
      priceMin: 800,
      priceMax: 15000,
      description: "Premium unisex salon known for bridal makeovers and advanced hair treatments. Uses L'Oréal and Schwarzkopf products exclusively. Voted Bangalore's Best Bridal Studio 2024.",
      genderServed: "all",
      ageGroups: "adults,teens",
      specialties: "Bridal Makeup,Hair Treatment,Keratin,Coloring,Facials",
      occasionTags: "Bridal,Party,Corporate,Spa,Express",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "L'Oréal,Schwarzkopf,OPI",
      specialtyTags: "Best for Hair Massage,Bridal Specialists,Express Service",
      yearsInBusiness: 12,
      happyCustomers: 15000,
      weeklyBookings: 87,
      nextSlot: "Today 3:30 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 95,
      distanceFromUser: 2.3,
      slotsLeftToday: 2,
      mostBookedFor: "Bridal Makeup"
    },
    {
      name: "Naturals Salon & Spa",
      area: "Indiranagar",
      address: "100 Feet Road, Indiranagar, Bangalore - 560038",
      rating: 4.6,
      reviewCount: 5670,
      imageUrl: "/images/salon-organic.png",
      whatsappNumber: "919845067890",
      phone: "080-25216789",
      priceRange: "₹",
      priceMin: 400,
      priceMax: 8000,
      description: "India's leading salon chain with organic product focus. Expert stylists for all hair types and skin care treatments. Family-friendly with dedicated kids corner.",
      genderServed: "all",
      ageGroups: "adults,teens,kids",
      specialties: "Haircuts,Hair Color,Skincare,Manicure,Pedicure",
      occasionTags: "Party,Corporate,Spa,Festival,Express,Family Day",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges,safe-for-kids",
      productBrands: "L'Oréal,Matrix,OPI",
      specialtyTags: "Organic Products,Relaxation Experts,Kids Corner Available",
      yearsInBusiness: 18,
      happyCustomers: 50000,
      weeklyBookings: 150,
      nextSlot: "Today 4:00 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: true,
      compatibilityScore: 88,
      distanceFromUser: 3.1,
      slotsLeftToday: 5,
      mostBookedFor: "Hair Coloring"
    },
    {
      name: "Juice Salon",
      area: "Whitefield",
      address: "ITPL Main Road, Whitefield, Bangalore - 560066",
      rating: 4.7,
      reviewCount: 3210,
      imageUrl: "/images/mehendi.png",
      whatsappNumber: "919845034567",
      phone: "080-28453456",
      priceRange: "₹",
      priceMin: 600,
      priceMax: 12000,
      description: "Award-winning luxury salon specializing in avant-garde hair designs and premium bridal packages. Known for international-standard color techniques.",
      genderServed: "women",
      ageGroups: "adults,teens",
      specialties: "Bridal Makeup,Hair Design,Extensions,Keratin,Spa",
      occasionTags: "Bridal,Party,Photoshoot,Festival,Express,Express Service",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "Schwarzkopf,Wella,Kérastase",
      specialtyTags: "Bridal Specialists,Top-Rated for Nails,Express Service",
      yearsInBusiness: 10,
      happyCustomers: 20000,
      weeklyBookings: 65,
      nextSlot: "Tomorrow 10:00 AM",
      isOpen: true,
      hasParking: true,
      hasExpressService: false,
      hasKidsCorner: false,
      compatibilityScore: 92,
      distanceFromUser: 8.5,
      slotsLeftToday: 0,
      mostBookedFor: "Hair Design"
    },
    {
      name: "Truefitt & Hill",
      area: "UB City Mall",
      address: "Level 3, UB City Mall, Vittal Mallya Road, Bangalore - 560001",
      rating: 4.9,
      reviewCount: 1890,
      imageUrl: "/images/salon-barber.png",
      whatsappNumber: "919845045678",
      phone: "080-41124567",
      priceRange: "₹",
      priceMin: 1500,
      priceMax: 20000,
      description: "Legendary British barbershop offering the finest men's grooming experience. Royal warrant holders since 1805. Hot towel shaves, beard sculpting, and premium facials.",
      genderServed: "men",
      ageGroups: "adults,teens",
      specialties: "Beard Grooming,Hair Styling,Facials,Royal Shave,Spa",
      occasionTags: "Corporate,Wedding Groom,Party,Spa",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "Truefitt & Hill,American Crew,Taylor of Old Bond Street",
      specialtyTags: "Best for Beard Grooming,Quick Corporate Looks,Parking Available",
      yearsInBusiness: 8,
      happyCustomers: 8000,
      weeklyBookings: 45,
      nextSlot: "Today 5:00 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 90,
      distanceFromUser: 4.2,
      slotsLeftToday: 3,
      mostBookedFor: "Beard Sculpting"
    },
    {
      name: "Lakmé Salon",
      area: "MG Road",
      address: "Brigade Road Junction, MG Road, Bangalore - 560001",
      rating: 4.5,
      reviewCount: 8920,
      imageUrl: "/images/salon-corporate.png",
      whatsappNumber: "919845056789",
      phone: "080-25567890",
      priceRange: "₹",
      priceMin: 300,
      priceMax: 6000,
      description: "India's most trusted beauty brand salon. Expert services for skin, hair, and bridal needs at accessible prices. 25 years of trusted beauty services.",
      genderServed: "all",
      ageGroups: "adults,teens,kids",
      specialties: "Facials,Haircuts,Coloring,Bridal,Nail Art",
      occasionTags: "Bridal,Party,Corporate,Festival,Spa,Express,Family Day",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges,safe-for-kids",
      productBrands: "Lakmé,Maybelline,L'Oréal",
      specialtyTags: "Top-Rated for Nails,Organic Products,Express Service",
      yearsInBusiness: 25,
      happyCustomers: 100000,
      weeklyBookings: 200,
      nextSlot: "Today 3:00 PM",
      isOpen: true,
      hasParking: false,
      hasExpressService: true,
      hasKidsCorner: true,
      compatibilityScore: 85,
      distanceFromUser: 1.8,
      slotsLeftToday: 8,
      mostBookedFor: "Facial Treatment"
    },
    {
      name: "Toni&Guy",
      area: "Lavelle Road",
      address: "Taj Residency, Lavelle Road, Bangalore - 560001",
      rating: 4.7,
      reviewCount: 4560,
      imageUrl: "/images/hero-salon.png",
      whatsappNumber: "919845078901",
      phone: "080-22247890",
      priceRange: "₹",
      priceMin: 1000,
      priceMax: 18000,
      description: "International hairdressing brand with world-class stylists. Known for precision cuts, balayage, and color correction techniques. Bangalore's go-to for hair transformations.",
      genderServed: "all",
      ageGroups: "adults,teens",
      specialties: "Precision Cuts,Balayage,Color Correction,Hair Spa",
      occasionTags: "Party,Corporate,Photoshoot,Festival,Express",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "Toni&Guy,Label.m,Wella",
      specialtyTags: "Best for Hair Massage,Express Service,Parking Available",
      yearsInBusiness: 15,
      happyCustomers: 25000,
      weeklyBookings: 95,
      nextSlot: "Today 4:30 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 93,
      distanceFromUser: 3.8,
      slotsLeftToday: 4,
      mostBookedFor: "Balayage"
    },
    {
      name: "Little Stars Kids Salon",
      area: "HSR Layout",
      address: "27th Main, Sector 2, HSR Layout, Bangalore - 560102",
      rating: 4.9,
      reviewCount: 890,
      imageUrl: "/images/salon-kids-fun.png",
      whatsappNumber: "919845089012",
      phone: "080-25588901",
      priceRange: "₹",
      priceMin: 200,
      priceMax: 3000,
      description: "Bangalore's first dedicated kids' salon with play areas, cartoon screens, and specially trained child-friendly stylists. CPSIA certified products only.",
      genderServed: "kids",
      ageGroups: "toddlers,kids,tweens,teens",
      specialties: "Kids Haircuts,Party Styling,Fancy Dress Makeover,Face Painting,Character Makeup,Nail Art",
      occasionTags: "Kids Party,Fancy Dress,Birthday,Festival,Face Painting,Makeover",
      verificationBadges: "verified,product-certified,hygiene-certified,no-hidden-charges,safe-for-kids",
      productBrands: "CPSIA Certified,Gentle Formula,Paraben-Free",
      specialtyTags: "Kids Corner Available,Fancy Dress & Face Paint Experts,Safe for Kids,Makeover Specialists",
      yearsInBusiness: 5,
      happyCustomers: 5000,
      weeklyBookings: 40,
      nextSlot: "Today 3:00 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: false,
      hasKidsCorner: true,
      compatibilityScore: 98,
      distanceFromUser: 5.2,
      slotsLeftToday: 6,
      mostBookedFor: "Fancy Dress & Face Paint"
    },
    {
      name: "Bliss Spa & Wellness",
      area: "Jayanagar",
      address: "4th Block, Jayanagar, Bangalore - 560011",
      rating: 4.8,
      reviewCount: 2100,
      imageUrl: "/images/salon-couples.png",
      whatsappNumber: "919845090123",
      phone: "080-26549012",
      priceRange: "₹",
      priceMin: 1000,
      priceMax: 10000,
      description: "Premium wellness center offering Ayurvedic spa treatments, aromatherapy, and holistic beauty therapies. Couples packages and solo retreats available.",
      genderServed: "all",
      ageGroups: "adults",
      specialties: "Ayurvedic Spa,Aromatherapy,Facials,Body Treatments,Couples Spa",
      occasionTags: "Spa,Couples Retreat,Self-Care,Festival",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "Kama Ayurveda,Forest Essentials,Biotique",
      specialtyTags: "Relaxation Experts,Organic Products,Couples Packages",
      yearsInBusiness: 8,
      happyCustomers: 12000,
      weeklyBookings: 55,
      nextSlot: "Today 5:30 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: false,
      hasKidsCorner: false,
      compatibilityScore: 87,
      distanceFromUser: 6.1,
      slotsLeftToday: 3,
      mostBookedFor: "Ayurvedic Spa"
    },
    {
      name: "Style Studios by Monisha",
      area: "JP Nagar",
      address: "15th Cross, JP Nagar Phase 1, Bangalore - 560078",
      rating: 4.6,
      reviewCount: 1780,
      imageUrl: "/images/party-glam.png",
      whatsappNumber: "919845001234",
      phone: "080-26580123",
      priceRange: "₹",
      priceMin: 500,
      priceMax: 8000,
      description: "Celebrity makeup artist Monisha's studio. Famous for party glam, mehendi, and engagement looks. Featured in Bangalore Times and Femina.",
      genderServed: "women",
      ageGroups: "adults,teens",
      specialties: "Party Makeup,Mehendi,Engagement Looks,Hair Styling,Nail Art",
      occasionTags: "Bridal,Party,Mehendi,Festival",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "MAC,Bobbi Brown,Charlotte Tilbury",
      specialtyTags: "Bridal Specialists,Top-Rated for Nails,Express Service",
      yearsInBusiness: 7,
      happyCustomers: 9000,
      weeklyBookings: 50,
      nextSlot: "Tomorrow 11:00 AM",
      isOpen: true,
      hasParking: false,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 91,
      distanceFromUser: 4.7,
      slotsLeftToday: 1,
      mostBookedFor: "Party Makeup"
    },
    {
      name: "The Man Company Grooming Lounge",
      area: "Marathahalli",
      address: "Sai Baba Temple Road, Marathahalli, Bangalore - 560037",
      rating: 4.5,
      reviewCount: 2340,
      imageUrl: "/images/hero-men.png",
      whatsappNumber: "919845012340",
      phone: "080-25231234",
      priceRange: "₹",
      priceMin: 400,
      priceMax: 5000,
      description: "Modern men's grooming lounge with express services for busy professionals. Quick lunch-break grooming available. Walk-ins welcome.",
      genderServed: "men",
      ageGroups: "adults,teens",
      specialties: "Beard Trimming,Hair Styling,Facials,Express Grooming",
      occasionTags: "Corporate,Party,Wedding Groom,Express",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "The Man Company,Beardo,Ustraa",
      specialtyTags: "Quick Corporate Looks,Express Service Available,Parking Available",
      yearsInBusiness: 6,
      happyCustomers: 18000,
      weeklyBookings: 70,
      nextSlot: "Today 3:15 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 86,
      distanceFromUser: 7.3,
      slotsLeftToday: 4,
      mostBookedFor: "Express Grooming"
    },
    {
      name: "VLCC Wellness Center",
      area: "Electronic City",
      address: "Phase 1, Electronic City, Bangalore - 560100",
      rating: 4.4,
      reviewCount: 6780,
      imageUrl: "/images/hero-spa.png",
      whatsappNumber: "919845023456",
      phone: "080-28522345",
      priceRange: "₹",
      priceMin: 500,
      priceMax: 7000,
      description: "India's leading wellness brand with comprehensive beauty, weight management, and skin care solutions. Trusted by 80,000+ customers in Bangalore.",
      genderServed: "all",
      ageGroups: "adults,teens",
      specialties: "Weight Management,Skin Treatments,Facials,Hair Removal,Spa",
      occasionTags: "Spa,Self-Care,Corporate,Festival,Express",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "VLCC,Naturecine",
      specialtyTags: "Relaxation Experts,Organic Products",
      yearsInBusiness: 20,
      happyCustomers: 80000,
      weeklyBookings: 120,
      nextSlot: "Today 4:00 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 82,
      distanceFromUser: 12.1,
      slotsLeftToday: 7,
      mostBookedFor: "Skin Treatment"
    },
    {
      name: "Blossom Kids & Family Salon",
      area: "Sarjapur Road",
      address: "Wipro Gate, Sarjapur Road, Bangalore - 560035",
      rating: 4.7,
      reviewCount: 1230,
      imageUrl: "/images/hero-kids.png",
      whatsappNumber: "919845034560",
      phone: "080-28543456",
      priceRange: "₹",
      priceMin: 300,
      priceMax: 5000,
      description: "Family-friendly salon with dedicated kids' zone. Gentle products, fun atmosphere, and expert stylists for all ages. First haircut certificate included!",
      genderServed: "all",
      ageGroups: "toddlers,kids,tweens,teens,adults",
      specialties: "Family Packages,Kids Haircuts,First Haircut,Mom-Daughter Spa,Fancy Dress Makeover,Face Painting",
      occasionTags: "Kids Party,Birthday,Fancy Dress,Family Day,Spa,Face Painting,Makeover",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges,safe-for-kids",
      productBrands: "Cetaphil,Himalaya,Paraben-Free Kids",
      specialtyTags: "Kids Corner Available,Fancy Dress & Face Paint Experts,Family Packages,Makeover Specialists",
      yearsInBusiness: 4,
      happyCustomers: 7000,
      weeklyBookings: 35,
      nextSlot: "Today 3:45 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: false,
      hasKidsCorner: true,
      compatibilityScore: 96,
      distanceFromUser: 9.8,
      slotsLeftToday: 5,
      mostBookedFor: "Family Package"
    },
    {
      name: "Glam Nail Studio",
      area: "Koramangala",
      address: "5th Block, Koramangala, Bangalore - 560034",
      rating: 4.8,
      reviewCount: 1560,
      imageUrl: "/images/salon-nails.png",
      whatsappNumber: "919845065432",
      phone: "080-25536543",
      priceRange: "₹",
      priceMin: 300,
      priceMax: 4000,
      description: "Bangalore's top-rated nail art studio specializing in intricate designs, gel extensions, and creative nail art. Instagram-worthy results every time.",
      genderServed: "women",
      ageGroups: "adults,teens",
      specialties: "Nail Art,Gel Extensions,Manicure,Pedicure,Nail Piercing",
      occasionTags: "Party,Bridal,Festival,Photoshoot,Express,Nail Art",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "OPI,Essie,CND",
      specialtyTags: "Top-Rated for Nails,Express Service Available",
      yearsInBusiness: 4,
      happyCustomers: 6000,
      weeklyBookings: 60,
      nextSlot: "Today 2:30 PM",
      isOpen: true,
      hasParking: false,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 89,
      distanceFromUser: 2.8,
      slotsLeftToday: 3,
      mostBookedFor: "Nail Art"
    },
    {
      name: "Ayush Ayurvedic Wellness",
      area: "Jayanagar",
      address: "11th Main, Jayanagar 4th Block, Bangalore - 560011",
      rating: 4.7,
      reviewCount: 980,
      imageUrl: "/images/influencer.png",
      whatsappNumber: "919845076543",
      phone: "080-26547654",
      priceRange: "₹",
      priceMin: 800,
      priceMax: 8000,
      description: "Authentic Ayurvedic beauty and wellness center. Traditional Kerala therapies, Panchakarma treatments, and herbal skincare. Pure organic products only.",
      genderServed: "all",
      ageGroups: "adults",
      specialties: "Panchakarma,Abhyanga,Shirodhara,Herbal Facials,Hair Treatment",
      occasionTags: "Spa,Self-Care,Couples Retreat,Festival",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "Kama Ayurveda,Forest Essentials,Kottakkal",
      specialtyTags: "Organic Products,Relaxation Experts,Couples Packages",
      yearsInBusiness: 15,
      happyCustomers: 10000,
      weeklyBookings: 40,
      nextSlot: "Today 4:00 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: false,
      hasKidsCorner: false,
      compatibilityScore: 84,
      distanceFromUser: 6.5,
      slotsLeftToday: 2,
      mostBookedFor: "Abhyanga Massage"
    },
    {
      name: "Urban Edge Men's Studio",
      area: "Indiranagar",
      address: "BDA Complex, Indiranagar, Bangalore - 560038",
      rating: 4.6,
      reviewCount: 1890,
      imageUrl: "/images/transformation.png",
      whatsappNumber: "919845087654",
      phone: "080-25218765",
      priceRange: "₹",
      priceMin: 600,
      priceMax: 8000,
      description: "Trendy men's grooming studio blending traditional barbering with modern techniques. Specializing in skin fades, beard art, and hair tattoos.",
      genderServed: "men",
      ageGroups: "adults,teens",
      specialties: "Skin Fades,Beard Art,Hair Tattoo,Facials,Hair Color",
      occasionTags: "Corporate,Party,Wedding Groom,Photoshoot,Express",
      verificationBadges: "verified,product-certified,hygiene-certified,reviews-50,no-hidden-charges",
      productBrands: "American Crew,Reuzel,Uppercut Deluxe",
      specialtyTags: "Best for Beard Grooming,Quick Corporate Looks,Parking Available",
      yearsInBusiness: 3,
      happyCustomers: 5500,
      weeklyBookings: 55,
      nextSlot: "Today 5:00 PM",
      isOpen: true,
      hasParking: true,
      hasExpressService: true,
      hasKidsCorner: false,
      compatibilityScore: 87,
      distanceFromUser: 3.5,
      slotsLeftToday: 4,
      mostBookedFor: "Skin Fade"
    },
    {
      name: "Tiny Tots Beauty Bar",
      area: "Whitefield",
      address: "ITPL Main Road, Whitefield, Bangalore - 560066",
      rating: 4.8,
      reviewCount: 650,
      imageUrl: "/images/hero-kids.png",
      whatsappNumber: "919845098765",
      phone: "080-28459876",
      priceRange: "₹",
      priceMin: 150,
      priceMax: 2500,
      description: "Whitefield's favorite kids' salon! Birthday party packages, fancy dress styling, and first haircut ceremonies. Certified child-safe products and trained staff.",
      genderServed: "kids",
      ageGroups: "toddlers,kids,tweens,teens",
      specialties: "First Haircut,Birthday Styling,Fancy Dress Makeover,Face Painting,Character Makeup,Gentle Spa",
      occasionTags: "Kids Party,Birthday,Fancy Dress,School Event,Face Painting,Makeover",
      verificationBadges: "verified,product-certified,hygiene-certified,no-hidden-charges,safe-for-kids",
      productBrands: "Babyganics,Himalaya Kids,Paraben-Free",
      specialtyTags: "Kids Corner Available,Fancy Dress & Face Paint Experts,Safe for Kids,Makeover Specialists",
      yearsInBusiness: 3,
      happyCustomers: 3000,
      weeklyBookings: 25,
      nextSlot: "Tomorrow 10:30 AM",
      isOpen: true,
      hasParking: true,
      hasExpressService: false,
      hasKidsCorner: true,
      compatibilityScore: 97,
      distanceFromUser: 9.2,
      slotsLeftToday: 4,
      mostBookedFor: "Birthday Makeover & Face Paint"
    }
  ];

  for (const salon of salons) {
    await db.salon.create({ data: salon });
  }
  console.log(`✅ Seeded ${salons.length} salons`);

  // Seed Testimonials
  const testimonials = [
    {
      name: "Priya Sharma",
      role: "Bride",
      avatarUrl: "/images/hero-bridal.png",
      content: "I was so nervous about my wedding day makeup, but Velvet and Veda connected me with the perfect artist. I felt like a queen! The salon was immaculate, products were premium, and the result was beyond my dreams.",
      rating: 5,
      serviceType: "Bridal Makeup",
      isVerified: true,
      helpfulYes: 234,
      helpfulNo: 3,
      imageUrl: "/images/hero-bridal.png"
    },
    {
      name: "Rahul Menon",
      role: "Software Engineer",
      avatarUrl: "/images/hero-men.png",
      content: "Last-minute date night panic! Found a salon 1km away with instant booking. Walked in stressed, walked out looking like a million bucks. My girlfriend was impressed!",
      rating: 5,
      serviceType: "Express Grooming",
      isVerified: true,
      helpfulYes: 156,
      helpfulNo: 2,
      imageUrl: "/images/hero-men.png"
    },
    {
      name: "Anjali Krishnamurthy",
      role: "Tech Lead at Google",
      avatarUrl: "/images/salon-corporate.png",
      content: "Finally, a place that understands corporate grooming needs. Got a professional look in 30 minutes before my big presentation. The AI matching found the perfect salon for my hair type!",
      rating: 5,
      serviceType: "Corporate Styling",
      isVerified: true,
      helpfulYes: 189,
      helpfulNo: 1,
      imageUrl: "/images/salon-corporate.png"
    },
    {
      name: "Meera Patel",
      role: "Mother of Two",
      avatarUrl: "/images/hero-kids.png",
      content: "My daughter's fancy dress competition was a hit! The salon was so patient and gentle with her. She looked like a little princess. The play area kept my son entertained too!",
      rating: 5,
      serviceType: "Kids Styling",
      isVerified: true,
      helpfulYes: 298,
      helpfulNo: 0,
      imageUrl: "/images/hero-kids.png"
    },
    {
      name: "Karan Reddy",
      role: "Startup Founder",
      avatarUrl: "/images/hero-men.png",
      content: "As a guy who never cared about grooming, this site made it easy. The AI recommended a salon based on my hair type and budget. Now I'm a regular! The verification badges give so much confidence.",
      rating: 4,
      serviceType: "Men's Grooming",
      isVerified: true,
      helpfulYes: 145,
      helpfulNo: 5,
      imageUrl: "/images/hero-men.png"
    },
    {
      name: "Deepa Nair",
      role: "Yoga Instructor",
      avatarUrl: "/images/hero-spa.png",
      content: "The self-care Sunday booking was exactly what I needed. Found a beautiful Ayurvedic spa through Velvet and Veda. The comparison feature helped me choose the best value. Pure bliss!",
      rating: 5,
      serviceType: "Spa & Wellness",
      isVerified: true,
      helpfulYes: 167,
      helpfulNo: 2,
      imageUrl: "/images/hero-spa.png"
    }
  ];

  for (const t of testimonials) {
    await db.testimonial.create({ data: t });
  }
  console.log(`✅ Seeded ${testimonials.length} testimonials`);

  // Seed Occasions
  const occasions = [
    { title: "Bridal Bliss", description: "Full makeup, mehendi, pre-wedding packages", emoji: "👰", color: "#6B1D2A", tags: "Bridal,Mehendi,Wedding", imageQuery: "Indian bride", sortOrder: 1 },
    { title: "Corporate Chic", description: "Quick fixes, professional looks, express services", emoji: "💼", color: "#3D3D3D", tags: "Corporate,Meeting,Office", imageQuery: "professional woman", sortOrder: 2 },
    { title: "Party Ready", description: "Glam makeup, party hair, nail art", emoji: "🎉", color: "#C5A059", tags: "Party,Glam,Night Out", imageQuery: "party makeup", sortOrder: 3 },
    { title: "Mehendi Magic", description: "Traditional bridal mehendi, modern designs", emoji: "🌸", color: "#6B1D2A", tags: "Mehendi,Bridal,Traditional", imageQuery: "henna hands", sortOrder: 4 },
    { title: "Spa & Relax", description: "De-stress, rejuvenate, unwind", emoji: "🧖", color: "#81B29A", tags: "Spa,Wellness,Relaxation", imageQuery: "spa treatment", sortOrder: 5 },
    { title: "Groom's Corner", description: "Beard styling, facial, hair, wedding prep", emoji: "🤵", color: "#3D3D3D", tags: "Men,Grooming,Wedding", imageQuery: "groom beard", sortOrder: 6 },
    { title: "Kids' Party Ready", description: "Fancy dress, birthday styling, first haircuts", emoji: "👶", color: "#FF6B6B", tags: "Kids,Party,Fancy Dress", imageQuery: "kids salon", sortOrder: 7 },
    { title: "Couples Retreat", description: "Packages for two, couple spa", emoji: "💑", color: "#C5A059", tags: "Couples,Spa,Romantic", imageQuery: "couple spa", sortOrder: 8 },
    { title: "Festival Glow", description: "Diwali, Christmas, New Year specials", emoji: "🎊", color: "#6B1D2A", tags: "Festival,Diwali,Christmas", imageQuery: "festival makeup", sortOrder: 9 },
    { title: "Fancy Dress Competition", description: "Kids' costume styling, face paint, character looks", emoji: "🎭", color: "#FF6B6B", tags: "Kids,Fancy Dress,School", imageQuery: "fancy dress kids", sortOrder: 10 },
    { title: "Photoshoot Ready", description: "Portfolio, LinkedIn, Instagram looks", emoji: "📸", color: "#3D3D3D", tags: "Photoshoot,Portfolio,Social Media", imageQuery: "photoshoot look", sortOrder: 11 },
    { title: "Self-Care Sunday", description: "Me-time, wellness, pampering", emoji: "🧘", color: "#81B29A", tags: "Self-Care,Wellness,Pamper", imageQuery: "self care spa", sortOrder: 12 }
  ];

  for (const o of occasions) {
    await db.occasion.create({ data: o });
  }
  console.log(`✅ Seeded ${occasions.length} occasions`);

  // Seed Blog Posts
  const blogPosts = [
    { title: "Top 10 Bridal Makeup Trends 2024", excerpt: "From dewy skin to bold eyes, discover the hottest bridal trends sweeping Bangalore this wedding season.", category: "Bridal", readTime: "8 min", slug: "bridal-makeup-trends-2024" },
    { title: "Quick Office Looks in 30 Minutes", excerpt: "Pressed for time? Here are 5 professional looks you can achieve during your lunch break.", category: "Corporate", readTime: "5 min", slug: "quick-office-looks" },
    { title: "Men's Grooming 101: The Complete Guide", excerpt: "Everything a modern gentleman needs to know about grooming, from beard care to skincare routines.", category: "Men", readTime: "10 min", slug: "mens-grooming-guide" },
    { title: "Kids' Hair Care: Tips for Parents", excerpt: "Making haircuts fun for kids. Expert tips on choosing the right salon and preparing your little one.", category: "Kids", readTime: "6 min", slug: "kids-hair-care-tips" },
    { title: "Best Salons for Curly Hair in Bangalore", excerpt: "Curly hair needs special care. We found the top salons that understand and celebrate your curls.", category: "Guide", readTime: "7 min", slug: "best-salons-curly-hair" }
  ];

  for (const b of blogPosts) {
    await db.blogPost.create({ data: b });
  }
  console.log(`✅ Seeded ${blogPosts.length} blog posts`);

  console.log('\n🎉 Velvet and Veda database seeded successfully!');
}

seed().catch(console.error);